macos_arm64_task:
  name: Build macOS arm64
  macos_instance:
    image: ghcr.io/cirruslabs/macos-monterey-xcode

  build_script: |
    brew install boost
    brew install vamp-plugin-sdk
    brew info --verbose boost
    make -f Makefile.osxarm64
    ls -l
    otool -L pyin.dylib

  binary_artifacts:
    path: ./*.dylib



