name: Build 

on: [push, pull_request]

jobs:

  build_linux:
    name: Build on linux
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build
        run: |
          sudo apt install libboost-math-dev
          cd vamp-plugin-sdk
          ./configure --enable-programs=no
          make clean
          make sdkstatic -j`nproc`
          cd ..
          make -f Makefile.linux64 -j`nproc`
          ls -l
          ldd pyin.so

      - uses: actions/upload-artifact@v3
        with:
          path: ./pyin.so

  build_macos:
    name: Build on macos
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build
        run: |
          brew install boost
          # brew install vamp-plugin-sdk
          cd vamp-plugin-sdk
          ./configure --enable-programs=no
          make clean
          make sdkstatic -j3
          cd ..
          make -f Makefile.osx
          ls -l
          otool -L pyin.dylib
          # ls -l /opt/homebrew/opt/vamp-plugin-sdk/lib


      - uses: actions/upload-artifact@v3
        with:
          path: ./pyin.dylib

